###
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "name":"boustor",
    "email": "courriel@courriel.com",
    "password": "123&Aabc",
    "admin":"0"
}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "admin@groupo.com",
    "password": "Super&2User"
}

###
GET http://localhost:3000/api/auth/ctrlToken
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTYyOTk4ODMxMywiZXhwIjoxNjI5OTk1NTEzfQ.Xc7mRWLiAuGH8Sfx0ohQdIm_J49x-rwWhA92vFzoZas

###
GET http://localhost:3000/api/messages
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTYzMDUyNjQ3OSwiZXhwIjoxNjMwNTMzNjc5fQ.GGww8Wu_aQkjP5EUOxLPmu04yEboZRIEeVLGRvKxKuE

###
GET http://localhost:3000/api/messages/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI2LCJpYXQiOjE2MjcxNDk5MTQsImV4cCI6MTYyNzE1NzExNH0.gsv3FmanUWhP-7H-ov-UUjUHxxyZW10AdN1KdVE0OJ0

###
POST http://localhost:3000/api/messages/update/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI2LCJpYXQiOjE2MjcxNjQ1NzAsImV4cCI6MTYyNzE3MTc3MH0.a_5ueHTuQ05B8yKVUhnworCaOn6RfQH9I8olbeXkViA

{
    "objet": "testmessage",
    "id_usr": 26,
    "message":"test de message et hop"
}

###
DELETE http://localhost:3000/api/sauces/60942e493298672d2c1b933d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDk1MGUxNDFhZWFiYjQ2NDQzYTA0NDYiLCJpYXQiOjE2MjA5NzgxNDIsImV4cCI6MTYyMTA2NDU0Mn0.s-EwKpQ_82R6Q5Fdpc3YxUprnh1WSpDVnHpow4-inzg

